# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00503834460d9e46ebc405d8713c775ebf8cea5fd4b24f273998ad1f0036506bba8ff3d2c5cf91ce4e39dd13f8af13ec16d28a8f8da07f53c7837398de22510f

test:
  secret_key_base: 4a4ab48a2023e739be503d213213d8bde74ba938724ebc1710aa77041ff71058140652cd9ff0fcad8a218ada46e423afc9568ae33b32e0a42bf84866f5cc3081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
